version: "3.9"

services:
  react-app:
    image: node:20.19.0-slim
    container_name: techpines-test-react-app
    working_dir: /app
    volumes:
      - ./:/app                  
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true